//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int CargoID { get; set; }
        public int ShippingID { get; set; }
        public int WarehouseID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
