//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.Status = "Processing";
            this.Weight = 0D;
            this.Height = 0D;
            this.Length = 0D;
            this.Width = 0D;
            this.Bookings = new HashSet<Booking>();
        }
    
        public int CargoID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string DeliveryAddress { get; set; }
        public double Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public int CustomerID { get; set; }

        public string Text
        {
            get { return Name.ToString() + " (" + Weight.ToString() + "kg)"; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
