//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ShippingID { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public string ShippingSource { get; set; }
        public string ShippingDestination { get; set; }

        public string Text
        {
            get { return ShippingDate.ToString("yyyy-MM-dd") + " (" + ShippingSource.ToString() + "->" + ShippingDestination.ToString() + ")"; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
